# Generated by Django 2.0.2 on 2018-02-13 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_site', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNum', models.IntegerField()),
                ('routingNum', models.IntegerField()),
                ('balance', models.FloatField(max_length=20)),
                ('acntType', models.CharField(max_length=15)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_site.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CheckRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_st', models.CharField(max_length=100)),
                ('address_city', models.CharField(max_length=100)),
                ('address_state', models.CharField(max_length=100)),
                ('address_zip', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core_files.Account')),
            ],
        ),
        migrations.CreateModel(
            name='DDRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('address_st', models.CharField(max_length=100)),
                ('address_city', models.CharField(max_length=100)),
                ('address_state', models.CharField(max_length=100)),
                ('address_zip', models.IntegerField()),
                ('rec_phone', models.IntegerField()),
                ('send_date', models.DateField()),
                ('payable_date', models.DateField()),
                ('message', models.CharField(max_length=240)),
                ('approved', models.BooleanField(default=False)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer_site.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accntTo', models.CharField(max_length=15)),
                ('dateTime', models.DateTimeField()),
                ('amount', models.FloatField(max_length=15)),
                ('accntFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_files.Account')),
            ],
        ),
    ]
