# Generated by Django 2.0.2 on 2018-02-13 22:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddrequest',
            name='payable_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ddrequest',
            name='send_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
