# Generated by Django 2.0.2 on 2018-02-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_files', '0002_auto_20180213_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
